# Generated by Django 3.2.13 on 2022-05-16 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=70, verbose_name='歌名')),
                ('singer', models.CharField(max_length=100, verbose_name='歌手')),
                ('song_image', models.ImageField(upload_to='pic/', verbose_name='歌曲封面')),
                ('song_file', models.FileField(upload_to='audio/', verbose_name='源文件')),
                ('upload_user', models.CharField(max_length=50, verbose_name='分享用户')),
                ('song_release', models.CharField(max_length=20, verbose_name='发行时间')),
            ],
            options={
                'verbose_name': '音乐',
                'verbose_name_plural': '音乐',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分类')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
            },
        ),
        migrations.CreateModel(
            name='Dynamic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dynamic_plays', models.IntegerField(verbose_name='播放次数')),
                ('dynamic_search', models.IntegerField(verbose_name='搜索次数')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.audio', verbose_name='歌名')),
            ],
            options={
                'verbose_name': '歌曲动态',
                'verbose_name_plural': '歌曲动态',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('comment_text', models.CharField(max_length=500, verbose_name='内容')),
                ('comment_user', models.CharField(max_length=20, verbose_name='用户')),
                ('comment_date', models.CharField(max_length=50, verbose_name='日期')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.audio', verbose_name='歌名')),
            ],
            options={
                'verbose_name': '歌曲评论',
                'verbose_name_plural': '歌曲评论',
            },
        ),
        migrations.AddField(
            model_name='audio',
            name='category',
            field=models.ManyToManyField(to='index.Category', verbose_name='分类'),
        ),
    ]
