# Generated by Django 3.2.13 on 2022-05-16 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='song_lrc',
            field=models.FileField(default=1, upload_to='lrc/', verbose_name='源文件'),
            preserve_default=False,
        ),
    ]
